# -*- coding: utf-8 -*-
{
	'name': 'POS Dashboard Ninja',

	'summary': """
Bring all your focus to the business with the POS Dashboard analytical tool. Gain valuable insights into your business & increase revenue in no time. Get going with every sale you make with Ksolves.,POS Dashboard Ninja,my pos dashboard, Odoo pos dashboard,pos dashboard Odoo apps,pos reports dashboard, pos system dashboard, POS Dashboard, Odoo Dashboard, Revamp Dashboard, Best Dashboard, Odoo Best Dashboard, Odoo Apps Dashboard, Best Ninja Dashboard, Analytic Dashboard, Pre-Configured Dashboard, Create Dashboard, Beautiful Dashboard, Customized Robust Dashboard, Predefined Dashboard, Multiple Dashboards, Advance Dashboard, Beautiful Powerful Dashboards All In One Dynamic Dashboard, Pie Chart Dashboard, Modern Dashboard, Dashboard Studio, Dashboard Builder, Dashboard Designer, Odoo Studio, Ksolves Dashboard, dashboard pos, point of sale dashboard, ERP dashboard,Point of sale module, Modify POS Dashboard app, Multicompany Dashboard,Odoo 14 dashboard, Odoo 15 dashboard , Powerful Dashboards, custom,Odoo dashboard, Modern Odoo Dashboards,Odoo 13 dashboard
""",

	'description': """
Dashboard Ninja,
        Odoo Dashboard,
        Dashboard,
        Odoo apps,
        Dashboard app,
        HR Dashboard,
        Sales Dashboard,
        inventory Dashboard,
        Lead Dashboard,
        Opportunity Dashboard,
        CRM Dashboard,
        POS,
        POS Dashboard,
        Connectors,
        Web Dynamic,
        Report Import/Export,
        Date Filter,
        HR,
        Sales,
        Theme,
        Tile Dashboard,
        Dashboard Widgets,
        Dashboard Manager,
        Debranding,
        Customize Dashboard,
        Graph Dashboard,
        Charts Dashboard,
        Invoice Dashboard,
        Project management,
        Ksolves,
        Point Of Sale,
        Point Of Sale Alert,
        POS,
        POS Dashboard
""",


  'author': "Ksolves India Ltd.",
  'license': 'OPL-1',
  'currency': 'EUR',
  'price': '22.4',
  'website': "https://store.ksolves.com/",
  'maintainer': 'Ksolves India Ltd.',
  'live_test_url': '',
  'category': 'Tools',
  'version': '16.0.1.0.0',
  'support': 'sales@ksolves.com',
  'images': ['static/description/Spring sale horizontal Odoo Video.gif'],
  'depends': ['base', 'web', 'ks_dashboard_ninja', 'base_setup', 'point_of_sale'],
  'data': ['data/ks_pos_sales_data.xml'],
}
